import type { Metadata } from "next";
import {Oswald} from 'next/font/google'
import "./globals.css";
import { ToastContainer } from "react-toastify";

const oswald = Oswald({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Calibre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={oswald.className}
      ><ToastContainer />
        {children}
      </body>
    </html>
  );
}
